const express=require('express');const path=require('path');const Database=require('better-sqlite3');const bcrypt=require('bcryptjs');const jwt=require('jsonwebtoken');const cookieParser=require('cookie-parser');
const app=express();app.use(express.json({limit:'100kb'}));app.use(cookieParser());app.use(express.static(path.join(__dirname,'public')));
const dataDir=process.env.DATA_DIR||path.join(__dirname,'data');
require('fs').mkdirSync(dataDir,{recursive:true});
const db=new Database(path.join(dataDir,'data.sqlite'));db.pragma('journal_mode=WAL');
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,email TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,points INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS tasks(id INTEGER PRIMARY KEY AUTOINCREMENT,title TEXT NOT NULL,description TEXT NOT NULL,url TEXT NOT NULL,points INTEGER NOT NULL DEFAULT 5,active INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS completions(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,task_id INTEGER NOT NULL,points INTEGER NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(user_id,task_id,created_at),FOREIGN KEY(user_id) REFERENCES users(id),FOREIGN KEY(task_id) REFERENCES tasks(id));CREATE TABLE IF NOT EXISTS point_ledger(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,amount INTEGER NOT NULL,reason TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id));`);
if(db.prepare('SELECT COUNT(*) c FROM tasks').get().c===0){const ins=db.prepare('INSERT INTO tasks(title,description,url,points) VALUES(?,?,?,?)');[['Khám phá kênh được đề xuất','Mở kênh và tự xem nội dung nếu bạn quan tâm.','https://www.tiktok.com/',5],['Khám phá nội dung cộng đồng','Xem nội dung được cộng đồng đề xuất. Không bắt buộc tương tác.','https://www.tiktok.com/',5],['Điểm danh hôm nay','Ghi nhận hoạt động cộng đồng trong ngày.','https://www.tiktok.com/',5]].forEach(x=>ins.run(...x));}
const SECRET=process.env.JWT_SECRET||'CHANGE_ME_IN_PRODUCTION';
function auth(req,res,next){try{const token=req.cookies.session;if(!token) return res.status(401).json({error:'Bạn chưa đăng nhập.'});req.user=jwt.verify(token,SECRET);next()}catch{return res.status(401).json({error:'Phiên đăng nhập đã hết hạn.'})}}
app.post('/api/register',(req,res)=>{const {name,email,password}=req.body||{};if(!name||!email||!password||password.length<6)return res.status(400).json({error:'Tên, email và mật khẩu từ 6 ký tự là bắt buộc.'});const e=email.trim().toLowerCase();try{const hash=bcrypt.hashSync(password,12);const r=db.prepare('INSERT INTO users(name,email,password_hash) VALUES(?,?,?)').run(name.trim(),e,hash);const token=jwt.sign({id:r.lastInsertRowid},SECRET,{expiresIn:'7d'});res.cookie('session',token,{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:604800000});res.json({ok:true})}catch(err){res.status(400).json({error:'Email đã được đăng ký.'})}});
app.post('/api/login',(req,res)=>{const {email,password}=req.body||{};const u=db.prepare('SELECT * FROM users WHERE email=?').get((email||'').trim().toLowerCase());if(!u||!bcrypt.compareSync(password||'',u.password_hash))return res.status(401).json({error:'Email hoặc mật khẩu không đúng.'});const token=jwt.sign({id:u.id},SECRET,{expiresIn:'7d'});res.cookie('session',token,{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:604800000});res.json({ok:true})});
app.post('/api/logout',(req,res)=>{res.clearCookie('session');res.json({ok:true})});
app.get('/api/me',auth,(req,res)=>{const u=db.prepare('SELECT id,name,email,points,created_at FROM users WHERE id=?').get(req.user.id);res.json(u)});
app.get('/api/tasks',auth,(req,res)=>{res.json(db.prepare('SELECT id,title,description,url,points FROM tasks WHERE active=1 ORDER BY id DESC').all())});
app.post('/api/tasks/:id/complete',auth,(req,res)=>{const task=db.prepare('SELECT * FROM tasks WHERE id=? AND active=1').get(req.params.id);if(!task)return res.status(404).json({error:'Nhiệm vụ không tồn tại.'});const exists=db.prepare("SELECT id FROM completions WHERE user_id=? AND task_id=? AND date(created_at)=date('now')").get(req.user.id,task.id);if(exists)return res.status(409).json({error:'Bạn đã hoàn thành nhiệm vụ này hôm nay.'});const tx=db.transaction(()=>{db.prepare('INSERT INTO completions(user_id,task_id,points) VALUES(?,?,?)').run(req.user.id,task.id,task.points);db.prepare('UPDATE users SET points=points+? WHERE id=?').run(task.points,req.user.id);db.prepare('INSERT INTO point_ledger(user_id,amount,reason) VALUES(?,?,?)').run(req.user.id,task.points,'Hoàn thành nhiệm vụ #'+task.id)});tx();res.json({ok:true,points:task.points})});
app.get('/api/leaderboard',(req,res)=>{const daily=db.prepare("SELECT name,points FROM users ORDER BY points DESC, id ASC LIMIT 10").all();const weekly=db.prepare("SELECT u.name,COALESCE(SUM(l.amount),0) points FROM users u LEFT JOIN point_ledger l ON l.user_id=u.id AND l.created_at>=datetime('now','-7 days') GROUP BY u.id ORDER BY points DESC,u.id ASC LIMIT 10").all();res.json({daily,weekly})});
app.get('/api/health',(req,res)=>res.json({ok:true}));
app.get('/*splat',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
const port=process.env.PORT||3000;app.listen(port,()=>console.log(`NhiemVuDiem V2 running on http://localhost:${port}`));
